title: Hacktoberfest Swag List
logo: /img/Hacktoberfest_2018_banner4.png
description: There are many companies giving out free swag for Hacktoberfest and this list seeks to find them all!
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
